### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'epic_blog.epicApp_category' doesn't exist")

### ISSUE THREAD

**Issue by hellyworld** [GhitaAlexandruIon/EpicBlog#5]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/helly/dev/scriucod/discipols/alex_ghita/EpicBlog/EpicBlog/urls.py", line 26, in <module>
    path('', include('epicApp.urls')),
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/helly/dev/scriucod/discipols/alex_ghita/EpicBlog/epicApp/urls.py", line 2, in <module>
    from epicApp.views import HomeView, PostDetailView, AddPostView, UpdatePostView, \
  File "/home/helly/dev/scriucod/discipols/alex_ghita/EpicBlog/epicApp/views.py", line 1, in <module>
    from epicApp.forms import PostForm, CommentForm
  File "/home/helly/dev/scriucod/discipols/alex_ghita/EpicBlog/epicApp/forms.py", line 6, in <module>
    for item in choices:
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/models/query.py", line 146, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1104, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/helly/dev/.venvs/scriucod/alex_ghita/EpicBlog/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'epic_blog.epicApp_category' doesn't exist")

**Comment by hellyworld** [comment]
try to clone the project in a new location and to start it, will not work!

**Comment by hellyworld** [comment]
Traceback tell me that you have a line in one of your files that is trying to use the epicApp_category model at import-time and, since you have not yet created the tables for that model to be valid, it's failing. 

`File "/home/helly/dev/scriucod/discipols/alex_ghita/EpicBlog/epicApp/forms.py", line 6, in
for item in choices:`

Either remove that line, or wrap it in a try...except so that it does not error when Django tries to import the module when you're running migrations.

`try:
    choices = Category.objects.all().values_list('name', 'name')
    choice_list = []
    for item in choices:
        choice_list.append(item)
except Exception as e:
    print(e)`

**Comment by hellyworld** [comment]
```choices = Category.objects.all().values_list('name', 'name')```

de ce aduci de doua ori 'name' ???

**Comment by GhitaAlexandruIon** [comment]
de ce aduci de doua ori 'name' ???
Ca e tuple
